package domain

import "git-garena.com/sea-labs-id/batch-04/stage-02/blanche/blanche-be/httperror"

var ErrUpdateMerchant = httperror.InternalServerError("failed to update merchant")
var ErrMerchantDomainNotFound = httperror.BadRequestError("cannot retrieve merchant information, merchant domain not found", "MERCHANT_NOT_FOUND")
var ErrMerchantStoreNameNotFound = httperror.BadRequestError("cannot retrieve merchant information, merchant store name not found", "MERCHANT_NOT_FOUND")
var ErrMerchantUserIDNotFound = httperror.BadRequestError("cannot retrieve merchant information, merchant owner user ID not found", "MERCHANT_NOT_FOUND")
var ErrMerchantUsernameNotFound = httperror.BadRequestError("cannot retrieve merchant information, merchant owner username not found", "MERCHANT_NOT_FOUND")
var ErrGetMerchant = httperror.InternalServerError("cannot get merchant record")
var ErrMerchantCityNotFound = httperror.BadRequestError("cannot retrieve merchant city information", "MERCHANT_CITY_NOT_FOUND")
var ErrMerchantAddressNotFound = httperror.BadRequestError("cannot retrieve merchant address information", "MERCHANT_ADDRESS_NOT_FOUND")
var ErrMerchantDomainUnique = httperror.BadRequestError("merchant domain already exists", "DOMAIN_ALREADY_EXISTS")
var ErrMerchantNameUnique = httperror.BadRequestError("merchant name already exists", "MERCHANT_NAME_ALREADY_EXISTS")
var ErrGetMerchantProductCategoryIds = httperror.InternalServerError("cannot get merchant product category Ids")
var ErrMerchantAlreadyRegistered = httperror.BadRequestError("this account already registered as merchant", "MERCHANT_ALREADY_REGISTERED")
var ErrGetMerchantVoucherList = httperror.InternalServerError("failed to get merchant voucher list")
var ErrGetMerchantVoucher = httperror.InternalServerError("failed to get merchant voucher record")
var ErrMerchantVoucherNotFound = httperror.BadRequestError("cannot retrieve merchant voucher information, merchant voucher not found", "MERCHANT_VOUCHER_NOT_FOUND")
var ErrDecreaseMerchantVoucherQuota = httperror.InternalServerError("failed to decrease merchant voucher quota")
var ErrMerchantFundActivitiesReqParam = httperror.BadRequestError("invalid request parameter for merchant fund activities", "INVALID_REQUEST_PARAM")
var ErrCreateMerchantVoucher = httperror.InternalServerError("failed to create merchant voucher")
var ErrInvalidVoucherDateRange = httperror.BadRequestError("voucher start date must before than voucher end date", "INVALID_VOUCHER_DATE_RANGE")
var ErrInvalidVoucherDateBeforeNow = httperror.BadRequestError("voucher start date or end date must after than today", "INVALID_VOUCHER_DATE_BEFORE_NOW")
var ErrDeleteMerchantVoucher = httperror.InternalServerError("failed to delete merchant voucher")
var ErrUpdateMerchantVoucher = httperror.InternalServerError("failed to update merchant voucher")
var ErrDelVoucherIsOngoing = httperror.BadRequestError("voucher is ongoing, cannot be deleted", "VOUCHER_IS_ONGOING")
var ErrMerchantVoucherCodeAlreadyExist = httperror.BadRequestError("voucher code already exist", "VOUCHER_CODE_ALREADY_EXIST")
var ErrUpdateVoucherCode = httperror.BadRequestError("unable to change the voucher code", "VOUCHER_CODE_CANNOT_CHANGE")
var ErrUpdateMerchantAddress = httperror.InternalServerError("failed to update merchant address")
var ErrUpdateOngoingVoucher = httperror.BadRequestError("voucher is ongoing, cannot update the start date", "VOUCHER_IS_ONGOING")

var ErrIncreaseMerchantNumOfSale = httperror.InternalServerError("failed to increase merchant number of sale")
var ErrUpdateMerchantRatingAndNumOfReview = httperror.InternalServerError("failed to update merchant rating and number of review")
